package com.zhicloud.ms.vo;

import java.math.BigDecimal;

public class CloudDisk {

	/**
	 *
	 * 自定义容量
	 */
   private String 	diskdiy;
	

	public String getDiskdiy() {
		return diskdiy;
	}

	public void setDiskdiy(String diskdiy) {
		this.diskdiy = diskdiy;
	}
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.real_disk_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String realDiskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.disk_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String diskPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.snapshot_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String snapshotPoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.user_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.name
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.account
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.password
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.disk
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private BigDecimal disk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.running_status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer runningStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.inner_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String innerIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.inner_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer innerPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.outer_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String outerIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.outer_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer outerPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.create_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.inactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String inactivateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.reactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String reactivateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.monthly_price
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private BigDecimal monthlyPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.region
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.iqn
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private String iqn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cloud_disk.type
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.id
	 * @return  the value of cloud_disk.id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.id
	 * @param id  the value for cloud_disk.id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.real_disk_id
	 * @return  the value of cloud_disk.real_disk_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getRealDiskId() {
		return realDiskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.real_disk_id
	 * @param realDiskId  the value for cloud_disk.real_disk_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setRealDiskId(String realDiskId) {
		this.realDiskId = realDiskId == null ? null : realDiskId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.disk_pool_id
	 * @return  the value of cloud_disk.disk_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getDiskPoolId() {
		return diskPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.disk_pool_id
	 * @param diskPoolId  the value for cloud_disk.disk_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setDiskPoolId(String diskPoolId) {
		this.diskPoolId = diskPoolId == null ? null : diskPoolId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.snapshot_pool_id
	 * @return  the value of cloud_disk.snapshot_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getSnapshotPoolId() {
		return snapshotPoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.snapshot_pool_id
	 * @param snapshotPoolId  the value for cloud_disk.snapshot_pool_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setSnapshotPoolId(String snapshotPoolId) {
		this.snapshotPoolId = snapshotPoolId == null ? null : snapshotPoolId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.user_id
	 * @return  the value of cloud_disk.user_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.user_id
	 * @param userId  the value for cloud_disk.user_id
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.name
	 * @return  the value of cloud_disk.name
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.name
	 * @param name  the value for cloud_disk.name
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.account
	 * @return  the value of cloud_disk.account
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.account
	 * @param account  the value for cloud_disk.account
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.password
	 * @return  the value of cloud_disk.password
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.password
	 * @param password  the value for cloud_disk.password
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.disk
	 * @return  the value of cloud_disk.disk
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public BigDecimal getDisk() {
		return disk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.disk
	 * @param disk  the value for cloud_disk.disk
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setDisk(BigDecimal disk) {
		this.disk = disk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.running_status
	 * @return  the value of cloud_disk.running_status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getRunningStatus() {
		return runningStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.running_status
	 * @param runningStatus  the value for cloud_disk.running_status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setRunningStatus(Integer runningStatus) {
		this.runningStatus = runningStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.status
	 * @return  the value of cloud_disk.status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.status
	 * @param status  the value for cloud_disk.status
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.inner_ip
	 * @return  the value of cloud_disk.inner_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getInnerIp() {
		return innerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.inner_ip
	 * @param innerIp  the value for cloud_disk.inner_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setInnerIp(String innerIp) {
		this.innerIp = innerIp == null ? null : innerIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.inner_port
	 * @return  the value of cloud_disk.inner_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getInnerPort() {
		return innerPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.inner_port
	 * @param innerPort  the value for cloud_disk.inner_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setInnerPort(Integer innerPort) {
		this.innerPort = innerPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.outer_ip
	 * @return  the value of cloud_disk.outer_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getOuterIp() {
		return outerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.outer_ip
	 * @param outerIp  the value for cloud_disk.outer_ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setOuterIp(String outerIp) {
		this.outerIp = outerIp == null ? null : outerIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.outer_port
	 * @return  the value of cloud_disk.outer_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getOuterPort() {
		return outerPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.outer_port
	 * @param outerPort  the value for cloud_disk.outer_port
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setOuterPort(Integer outerPort) {
		this.outerPort = outerPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.create_time
	 * @return  the value of cloud_disk.create_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.create_time
	 * @param createTime  the value for cloud_disk.create_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.inactivate_time
	 * @return  the value of cloud_disk.inactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getInactivateTime() {
		return inactivateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.inactivate_time
	 * @param inactivateTime  the value for cloud_disk.inactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setInactivateTime(String inactivateTime) {
		this.inactivateTime = inactivateTime == null ? null : inactivateTime
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.reactivate_time
	 * @return  the value of cloud_disk.reactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getReactivateTime() {
		return reactivateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.reactivate_time
	 * @param reactivateTime  the value for cloud_disk.reactivate_time
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setReactivateTime(String reactivateTime) {
		this.reactivateTime = reactivateTime == null ? null : reactivateTime
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.monthly_price
	 * @return  the value of cloud_disk.monthly_price
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public BigDecimal getMonthlyPrice() {
		return monthlyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.monthly_price
	 * @param monthlyPrice  the value for cloud_disk.monthly_price
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setMonthlyPrice(BigDecimal monthlyPrice) {
		this.monthlyPrice = monthlyPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.region
	 * @return  the value of cloud_disk.region
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.region
	 * @param region  the value for cloud_disk.region
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setRegion(Integer region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.ip
	 * @return  the value of cloud_disk.ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.ip
	 * @param ip  the value for cloud_disk.ip
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.iqn
	 * @return  the value of cloud_disk.iqn
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public String getIqn() {
		return iqn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.iqn
	 * @param iqn  the value for cloud_disk.iqn
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setIqn(String iqn) {
		this.iqn = iqn == null ? null : iqn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cloud_disk.type
	 * @return  the value of cloud_disk.type
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cloud_disk.type
	 * @param type  the value for cloud_disk.type
	 * @mbggenerated  Wed Aug 05 15:14:52 CST 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}
	
    public String getDisk_name() {
        Float temp = disk.floatValue() / 1024 / 1024 / 1024;
        long l1 = Math.round(temp * 100); // 四舍五入
        double ret = l1 / 100.0;
        return ret + "GB";
    }
    
    public String getType_name() {
        if (type == 0) {
            return "普通磁盘";
        } else {
            return "高速磁盘";
        }
    }
    
    public String getRunningstatus_name() {
        if (runningStatus == 1) {
            return "关机";
        } else if (runningStatus == 2) {
            return "启动";
        } else if (runningStatus == 3) {
            return "故障";
        } else if (runningStatus == 4) {
            return "停机";
        }
        return "";
    }
    
    public String getStatus_name() {
        if (status == 1) {
            return "正常";
        } else if (status == 2) {
            return "停机";
        } else if (status == 3) {
            return "欠费";
        } else if (status == 4) {
            return "永久停机";
        }
        return "";
    }
}