package com.zhicloud.ms.vo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CloudDiskExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public CloudDiskExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdIsNull() {
			addCriterion("real_disk_id is null");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdIsNotNull() {
			addCriterion("real_disk_id is not null");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdEqualTo(String value) {
			addCriterion("real_disk_id =", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdNotEqualTo(String value) {
			addCriterion("real_disk_id <>", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdGreaterThan(String value) {
			addCriterion("real_disk_id >", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdGreaterThanOrEqualTo(String value) {
			addCriterion("real_disk_id >=", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdLessThan(String value) {
			addCriterion("real_disk_id <", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdLessThanOrEqualTo(String value) {
			addCriterion("real_disk_id <=", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdLike(String value) {
			addCriterion("real_disk_id like", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdNotLike(String value) {
			addCriterion("real_disk_id not like", value, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdIn(List<String> values) {
			addCriterion("real_disk_id in", values, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdNotIn(List<String> values) {
			addCriterion("real_disk_id not in", values, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdBetween(String value1, String value2) {
			addCriterion("real_disk_id between", value1, value2, "realDiskId");
			return (Criteria) this;
		}

		public Criteria andRealDiskIdNotBetween(String value1, String value2) {
			addCriterion("real_disk_id not between", value1, value2,
					"realDiskId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdIsNull() {
			addCriterion("disk_pool_id is null");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdIsNotNull() {
			addCriterion("disk_pool_id is not null");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdEqualTo(String value) {
			addCriterion("disk_pool_id =", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdNotEqualTo(String value) {
			addCriterion("disk_pool_id <>", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdGreaterThan(String value) {
			addCriterion("disk_pool_id >", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdGreaterThanOrEqualTo(String value) {
			addCriterion("disk_pool_id >=", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdLessThan(String value) {
			addCriterion("disk_pool_id <", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdLessThanOrEqualTo(String value) {
			addCriterion("disk_pool_id <=", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdLike(String value) {
			addCriterion("disk_pool_id like", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdNotLike(String value) {
			addCriterion("disk_pool_id not like", value, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdIn(List<String> values) {
			addCriterion("disk_pool_id in", values, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdNotIn(List<String> values) {
			addCriterion("disk_pool_id not in", values, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdBetween(String value1, String value2) {
			addCriterion("disk_pool_id between", value1, value2, "diskPoolId");
			return (Criteria) this;
		}

		public Criteria andDiskPoolIdNotBetween(String value1, String value2) {
			addCriterion("disk_pool_id not between", value1, value2,
					"diskPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdIsNull() {
			addCriterion("snapshot_pool_id is null");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdIsNotNull() {
			addCriterion("snapshot_pool_id is not null");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdEqualTo(String value) {
			addCriterion("snapshot_pool_id =", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdNotEqualTo(String value) {
			addCriterion("snapshot_pool_id <>", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdGreaterThan(String value) {
			addCriterion("snapshot_pool_id >", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdGreaterThanOrEqualTo(String value) {
			addCriterion("snapshot_pool_id >=", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdLessThan(String value) {
			addCriterion("snapshot_pool_id <", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdLessThanOrEqualTo(String value) {
			addCriterion("snapshot_pool_id <=", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdLike(String value) {
			addCriterion("snapshot_pool_id like", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdNotLike(String value) {
			addCriterion("snapshot_pool_id not like", value, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdIn(List<String> values) {
			addCriterion("snapshot_pool_id in", values, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdNotIn(List<String> values) {
			addCriterion("snapshot_pool_id not in", values, "snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdBetween(String value1, String value2) {
			addCriterion("snapshot_pool_id between", value1, value2,
					"snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andSnapshotPoolIdNotBetween(String value1, String value2) {
			addCriterion("snapshot_pool_id not between", value1, value2,
					"snapshotPoolId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAccountIsNull() {
			addCriterion("account is null");
			return (Criteria) this;
		}

		public Criteria andAccountIsNotNull() {
			addCriterion("account is not null");
			return (Criteria) this;
		}

		public Criteria andAccountEqualTo(String value) {
			addCriterion("account =", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotEqualTo(String value) {
			addCriterion("account <>", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThan(String value) {
			addCriterion("account >", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThanOrEqualTo(String value) {
			addCriterion("account >=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThan(String value) {
			addCriterion("account <", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThanOrEqualTo(String value) {
			addCriterion("account <=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLike(String value) {
			addCriterion("account like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotLike(String value) {
			addCriterion("account not like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountIn(List<String> values) {
			addCriterion("account in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotIn(List<String> values) {
			addCriterion("account not in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountBetween(String value1, String value2) {
			addCriterion("account between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotBetween(String value1, String value2) {
			addCriterion("account not between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andDiskIsNull() {
			addCriterion("disk is null");
			return (Criteria) this;
		}

		public Criteria andDiskIsNotNull() {
			addCriterion("disk is not null");
			return (Criteria) this;
		}

		public Criteria andDiskEqualTo(BigDecimal value) {
			addCriterion("disk =", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskNotEqualTo(BigDecimal value) {
			addCriterion("disk <>", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskGreaterThan(BigDecimal value) {
			addCriterion("disk >", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("disk >=", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskLessThan(BigDecimal value) {
			addCriterion("disk <", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskLessThanOrEqualTo(BigDecimal value) {
			addCriterion("disk <=", value, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskIn(List<BigDecimal> values) {
			addCriterion("disk in", values, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskNotIn(List<BigDecimal> values) {
			addCriterion("disk not in", values, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("disk between", value1, value2, "disk");
			return (Criteria) this;
		}

		public Criteria andDiskNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("disk not between", value1, value2, "disk");
			return (Criteria) this;
		}

		public Criteria andRunningStatusIsNull() {
			addCriterion("running_status is null");
			return (Criteria) this;
		}

		public Criteria andRunningStatusIsNotNull() {
			addCriterion("running_status is not null");
			return (Criteria) this;
		}

		public Criteria andRunningStatusEqualTo(Integer value) {
			addCriterion("running_status =", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusNotEqualTo(Integer value) {
			addCriterion("running_status <>", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusGreaterThan(Integer value) {
			addCriterion("running_status >", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("running_status >=", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusLessThan(Integer value) {
			addCriterion("running_status <", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusLessThanOrEqualTo(Integer value) {
			addCriterion("running_status <=", value, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusIn(List<Integer> values) {
			addCriterion("running_status in", values, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusNotIn(List<Integer> values) {
			addCriterion("running_status not in", values, "runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusBetween(Integer value1, Integer value2) {
			addCriterion("running_status between", value1, value2,
					"runningStatus");
			return (Criteria) this;
		}

		public Criteria andRunningStatusNotBetween(Integer value1,
				Integer value2) {
			addCriterion("running_status not between", value1, value2,
					"runningStatus");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andInnerIpIsNull() {
			addCriterion("inner_ip is null");
			return (Criteria) this;
		}

		public Criteria andInnerIpIsNotNull() {
			addCriterion("inner_ip is not null");
			return (Criteria) this;
		}

		public Criteria andInnerIpEqualTo(String value) {
			addCriterion("inner_ip =", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpNotEqualTo(String value) {
			addCriterion("inner_ip <>", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpGreaterThan(String value) {
			addCriterion("inner_ip >", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpGreaterThanOrEqualTo(String value) {
			addCriterion("inner_ip >=", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpLessThan(String value) {
			addCriterion("inner_ip <", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpLessThanOrEqualTo(String value) {
			addCriterion("inner_ip <=", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpLike(String value) {
			addCriterion("inner_ip like", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpNotLike(String value) {
			addCriterion("inner_ip not like", value, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpIn(List<String> values) {
			addCriterion("inner_ip in", values, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpNotIn(List<String> values) {
			addCriterion("inner_ip not in", values, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpBetween(String value1, String value2) {
			addCriterion("inner_ip between", value1, value2, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerIpNotBetween(String value1, String value2) {
			addCriterion("inner_ip not between", value1, value2, "innerIp");
			return (Criteria) this;
		}

		public Criteria andInnerPortIsNull() {
			addCriterion("inner_port is null");
			return (Criteria) this;
		}

		public Criteria andInnerPortIsNotNull() {
			addCriterion("inner_port is not null");
			return (Criteria) this;
		}

		public Criteria andInnerPortEqualTo(Integer value) {
			addCriterion("inner_port =", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortNotEqualTo(Integer value) {
			addCriterion("inner_port <>", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortGreaterThan(Integer value) {
			addCriterion("inner_port >", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortGreaterThanOrEqualTo(Integer value) {
			addCriterion("inner_port >=", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortLessThan(Integer value) {
			addCriterion("inner_port <", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortLessThanOrEqualTo(Integer value) {
			addCriterion("inner_port <=", value, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortIn(List<Integer> values) {
			addCriterion("inner_port in", values, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortNotIn(List<Integer> values) {
			addCriterion("inner_port not in", values, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortBetween(Integer value1, Integer value2) {
			addCriterion("inner_port between", value1, value2, "innerPort");
			return (Criteria) this;
		}

		public Criteria andInnerPortNotBetween(Integer value1, Integer value2) {
			addCriterion("inner_port not between", value1, value2, "innerPort");
			return (Criteria) this;
		}

		public Criteria andOuterIpIsNull() {
			addCriterion("outer_ip is null");
			return (Criteria) this;
		}

		public Criteria andOuterIpIsNotNull() {
			addCriterion("outer_ip is not null");
			return (Criteria) this;
		}

		public Criteria andOuterIpEqualTo(String value) {
			addCriterion("outer_ip =", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpNotEqualTo(String value) {
			addCriterion("outer_ip <>", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpGreaterThan(String value) {
			addCriterion("outer_ip >", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpGreaterThanOrEqualTo(String value) {
			addCriterion("outer_ip >=", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpLessThan(String value) {
			addCriterion("outer_ip <", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpLessThanOrEqualTo(String value) {
			addCriterion("outer_ip <=", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpLike(String value) {
			addCriterion("outer_ip like", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpNotLike(String value) {
			addCriterion("outer_ip not like", value, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpIn(List<String> values) {
			addCriterion("outer_ip in", values, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpNotIn(List<String> values) {
			addCriterion("outer_ip not in", values, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpBetween(String value1, String value2) {
			addCriterion("outer_ip between", value1, value2, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterIpNotBetween(String value1, String value2) {
			addCriterion("outer_ip not between", value1, value2, "outerIp");
			return (Criteria) this;
		}

		public Criteria andOuterPortIsNull() {
			addCriterion("outer_port is null");
			return (Criteria) this;
		}

		public Criteria andOuterPortIsNotNull() {
			addCriterion("outer_port is not null");
			return (Criteria) this;
		}

		public Criteria andOuterPortEqualTo(Integer value) {
			addCriterion("outer_port =", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortNotEqualTo(Integer value) {
			addCriterion("outer_port <>", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortGreaterThan(Integer value) {
			addCriterion("outer_port >", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortGreaterThanOrEqualTo(Integer value) {
			addCriterion("outer_port >=", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortLessThan(Integer value) {
			addCriterion("outer_port <", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortLessThanOrEqualTo(Integer value) {
			addCriterion("outer_port <=", value, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortIn(List<Integer> values) {
			addCriterion("outer_port in", values, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortNotIn(List<Integer> values) {
			addCriterion("outer_port not in", values, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortBetween(Integer value1, Integer value2) {
			addCriterion("outer_port between", value1, value2, "outerPort");
			return (Criteria) this;
		}

		public Criteria andOuterPortNotBetween(Integer value1, Integer value2) {
			addCriterion("outer_port not between", value1, value2, "outerPort");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("create_time like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("create_time not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeIsNull() {
			addCriterion("inactivate_time is null");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeIsNotNull() {
			addCriterion("inactivate_time is not null");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeEqualTo(String value) {
			addCriterion("inactivate_time =", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeNotEqualTo(String value) {
			addCriterion("inactivate_time <>", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeGreaterThan(String value) {
			addCriterion("inactivate_time >", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("inactivate_time >=", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeLessThan(String value) {
			addCriterion("inactivate_time <", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeLessThanOrEqualTo(String value) {
			addCriterion("inactivate_time <=", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeLike(String value) {
			addCriterion("inactivate_time like", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeNotLike(String value) {
			addCriterion("inactivate_time not like", value, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeIn(List<String> values) {
			addCriterion("inactivate_time in", values, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeNotIn(List<String> values) {
			addCriterion("inactivate_time not in", values, "inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeBetween(String value1, String value2) {
			addCriterion("inactivate_time between", value1, value2,
					"inactivateTime");
			return (Criteria) this;
		}

		public Criteria andInactivateTimeNotBetween(String value1, String value2) {
			addCriterion("inactivate_time not between", value1, value2,
					"inactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeIsNull() {
			addCriterion("reactivate_time is null");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeIsNotNull() {
			addCriterion("reactivate_time is not null");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeEqualTo(String value) {
			addCriterion("reactivate_time =", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeNotEqualTo(String value) {
			addCriterion("reactivate_time <>", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeGreaterThan(String value) {
			addCriterion("reactivate_time >", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("reactivate_time >=", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeLessThan(String value) {
			addCriterion("reactivate_time <", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeLessThanOrEqualTo(String value) {
			addCriterion("reactivate_time <=", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeLike(String value) {
			addCriterion("reactivate_time like", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeNotLike(String value) {
			addCriterion("reactivate_time not like", value, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeIn(List<String> values) {
			addCriterion("reactivate_time in", values, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeNotIn(List<String> values) {
			addCriterion("reactivate_time not in", values, "reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeBetween(String value1, String value2) {
			addCriterion("reactivate_time between", value1, value2,
					"reactivateTime");
			return (Criteria) this;
		}

		public Criteria andReactivateTimeNotBetween(String value1, String value2) {
			addCriterion("reactivate_time not between", value1, value2,
					"reactivateTime");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceIsNull() {
			addCriterion("monthly_price is null");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceIsNotNull() {
			addCriterion("monthly_price is not null");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceEqualTo(BigDecimal value) {
			addCriterion("monthly_price =", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceNotEqualTo(BigDecimal value) {
			addCriterion("monthly_price <>", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceGreaterThan(BigDecimal value) {
			addCriterion("monthly_price >", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("monthly_price >=", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceLessThan(BigDecimal value) {
			addCriterion("monthly_price <", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("monthly_price <=", value, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceIn(List<BigDecimal> values) {
			addCriterion("monthly_price in", values, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceNotIn(List<BigDecimal> values) {
			addCriterion("monthly_price not in", values, "monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("monthly_price between", value1, value2,
					"monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andMonthlyPriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("monthly_price not between", value1, value2,
					"monthlyPrice");
			return (Criteria) this;
		}

		public Criteria andRegionIsNull() {
			addCriterion("region is null");
			return (Criteria) this;
		}

		public Criteria andRegionIsNotNull() {
			addCriterion("region is not null");
			return (Criteria) this;
		}

		public Criteria andRegionEqualTo(Integer value) {
			addCriterion("region =", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotEqualTo(Integer value) {
			addCriterion("region <>", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThan(Integer value) {
			addCriterion("region >", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionGreaterThanOrEqualTo(Integer value) {
			addCriterion("region >=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThan(Integer value) {
			addCriterion("region <", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionLessThanOrEqualTo(Integer value) {
			addCriterion("region <=", value, "region");
			return (Criteria) this;
		}

		public Criteria andRegionIn(List<Integer> values) {
			addCriterion("region in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotIn(List<Integer> values) {
			addCriterion("region not in", values, "region");
			return (Criteria) this;
		}

		public Criteria andRegionBetween(Integer value1, Integer value2) {
			addCriterion("region between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andRegionNotBetween(Integer value1, Integer value2) {
			addCriterion("region not between", value1, value2, "region");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIqnIsNull() {
			addCriterion("iqn is null");
			return (Criteria) this;
		}

		public Criteria andIqnIsNotNull() {
			addCriterion("iqn is not null");
			return (Criteria) this;
		}

		public Criteria andIqnEqualTo(String value) {
			addCriterion("iqn =", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnNotEqualTo(String value) {
			addCriterion("iqn <>", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnGreaterThan(String value) {
			addCriterion("iqn >", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnGreaterThanOrEqualTo(String value) {
			addCriterion("iqn >=", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnLessThan(String value) {
			addCriterion("iqn <", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnLessThanOrEqualTo(String value) {
			addCriterion("iqn <=", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnLike(String value) {
			addCriterion("iqn like", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnNotLike(String value) {
			addCriterion("iqn not like", value, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnIn(List<String> values) {
			addCriterion("iqn in", values, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnNotIn(List<String> values) {
			addCriterion("iqn not in", values, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnBetween(String value1, String value2) {
			addCriterion("iqn between", value1, value2, "iqn");
			return (Criteria) this;
		}

		public Criteria andIqnNotBetween(String value1, String value2) {
			addCriterion("iqn not between", value1, value2, "iqn");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cloud_disk
	 * @mbggenerated  Wed Aug 05 15:14:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_disk
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 03 14:50:28 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}