package com.zhicloud.ms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zhicloud.ms.vo.CloudDisk;
import com.zhicloud.ms.vo.CloudDiskExample;

public interface CloudDiskMapper {
	

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    List<CloudDisk> selectAll();
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int countByExample(CloudDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int deleteByExample(CloudDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int insert(CloudDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int insertSelective(CloudDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    List<CloudDisk> selectByExample(CloudDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    CloudDisk selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") CloudDisk record, @Param("example") CloudDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int updateByExample(@Param("record") CloudDisk record, @Param("example") CloudDiskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int updateByPrimaryKeySelective(CloudDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_disk
     *
     * @mbggenerated Mon Aug 03 14:44:19 CST 2015
     */
    int updateByPrimaryKey(CloudDisk record);
}